### ISSUE TITLE
Controller Slave!

### ISSUE THREAD

**Issue by Afewbabygiraffes** [Belgabor/DrawersBits#10]
It's all entirely possible I'm not using it correctly.. but the controller slave doesn't seem to be working for my setup. which I'll post below. Along with the diagram below, I also tried putting the slave further away(11 and 12 blocks from the controller to the right) and right next to it. 
The controller and Slave are at the bottom. It's one giant wall, with some spaces for windows/doors. The X's just distort the rectangle a little

D=Drawers(compact or regular storage)
C=Controller
S=Slave
X=EmptySpace

DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDD
DDDXXXDDDDDDDDDDDXXXDDD
DDDXXXDDDDXXXXDDXXXDDDD
DDDDDDDDDCXXXXSDDDDDDDD

**Comment by Belgabor** [comment]
That should work, how are you trying to insert into the slave? Is whatever you are trying to insert already in the system? Does it work with a regular controller?
Try a hopper, see if that works.

Also which version are we talking about, both Storage Drawers and Drawers & Bits?

**Comment by Afewbabygiraffes** [comment]
I'm on the FTB Beyond package, I can check which version if you'd like.

and let me explain a little more.
So I'm trying to have access to ALL the drawers from the controller. but the last 2 rows on the right, don't have access(I've tested this by inserting Redstone, and noticing the redstone goes to an empty drawer instead of the ones on the far right.) The last two rows are 14 blocks away from the controller(I know the controller has a limit of 12) but I thought the Slave extended that range slightly, however it still didn't get access to the last 2 rows. so in essence, the slave isn't doing anything.

Things are inserted into the controller just fine, I have no problems with that. Just the slave not extending the range

 

    On Monday, March 13, 2017 4:29 PM, Belgabor <notifications@github.com> wrote:
 

 That should work, how are you trying to insert into the slave? Is whatever you are trying to insert already in the system? Does it work with a regular controller?
Try a hopper, see if that works.Also which version are we talking about, both Storage Drawers and Drawers & Bits?—

**Comment by Belgabor** [comment]
OH! The slave does not extend the range, that's a myth someone started way back, it never did. The only thing the slave does is add another insertion point.

**Comment by Afewbabygiraffes** [comment]
Dangit! Okay, my apologies then! 

    On Monday, March 13, 2017 4:58 PM, Belgabor <notifications@github.com> wrote:
 

 OH! The slave does not extend the range, that's a myth someone started way back, it never did. The only thing the slave does is add another insertion point.—

**Comment by Belgabor** [comment]
No worries, it's a persistent belief XD
