### ISSUE TITLE
crash after updating storage drawers to StorageDrawers-1.10.2-3.3.0

### ISSUE THREAD

**Issue by SDUBZ** [Belgabor/DrawersBits#5]
crashlog:
[crash-2016-10-30_05.01.30-client.txt](https://github.com/Belgabor/DrawersBits/files/560068/crash-2016-10-30_05.01.30-client.txt)

please fix soon

**Comment by jaquadro** [comment]
A breaking change was introduced when I accepted a PR to refactor some of the back-end code for better compatibility with world protection systems.

**Comment by SDUBZ** [comment]
oh ok so how do we go forward with future updates regarding storage drawers?

**Comment by MakerTim** [comment]
Same error here :/
got it since i updated storagedrawers 

http://pastebin.com/SR1av3ye

**Comment by Belgabor** [comment]
I'll take a look at it.

**Comment by Belgabor** [comment]
Fixed in 0.32
