### ISSUE TITLE
instant Server crash

### ISSUE THREAD

**Issue by scalda** [Belgabor/DrawersBits#6]
Hi i have just updated my test server for the hermitpack with the latest versions of your mod and storage drawers and I am now getting this crash every time the world loads, I have disabled your mod for the time being

Please find the crash log here [http://pastebin.com/VhwPVNPy](url)

Regards 

Scalda

**Comment by Belgabor** [comment]
Probably an issue with SD 3.4+. Will look into it.

**Comment by Belgabor** [comment]
Fixed in 0.33
