### ISSUE TITLE
Bit Drawer Controller bug

### ISSUE THREAD

**Issue by eranor** [Belgabor/DrawersBits#7]
Hi. I've noticed that when I break the bit drawer controller it stays in the world, but I also get the block as an item when using Drawers & Bits version 1.10.2-0.33 and Chisels & Bits version 12.7.
I've got a message at starting the game that this version was not yet updated for the newest C&B.
Could this be the cause of the bug?

Thanks.

**Comment by Belgabor** [comment]
No, that's an issue I missed when updating to SD 3.4.X. Thanks for reporting.

**Comment by Belgabor** [comment]
Fixed in 0.34
